---
title: "compile_2017-2019"
output: html_document
---

Load libraries, find the R-project root directory, and specify input/output files.
```{r}
library(tidyverse)
root.dir <- rprojroot::find_root("chem_hist_cleaning.Rproj")

##### User-defined variables #####

# Must create the directories specified in input.path and output.path #
input.path <- file.path(root.dir, "data", "2017-2019")
output.path <- file.path(root.dir, "data", "2017-2019", "output")

output.filename.sample <- paste0("S_CHEM_HISTORY_SAMPLE-2017-2019_", Sys.Date(), ".csv")
output.filename.result <- paste0("S_CHEM_HISTORY_RESULT-2017-2019_", Sys.Date(), ".csv")
output.filename.batch <- paste0("S_CHEM_HISTORY_BATCH-2017-2019_", Sys.Date(), ".csv")

#Specify sites reference table
# sites.master <- read.csv(file.path(root.dir, "data_input/site_tables/20191224_Site_Field_cleaned_final.csv"))

##################################

```


Load in SAMPLE, RESULT, and BATCH files.
```{r}

SAMPLE.2017 <- read_csv(file.path(root.dir, "data/2017-2019/2017_chem_preqaqc_SAMPLE-SBU_complete_2020-03-26.csv"))
SAMPLE.2018 <- read_csv(file.path(root.dir, "data/2017-2019/2018_chem_preqaqc_SAMPLE-SBU_complete_2020-03-25.csv"))
SAMPLE.2019 <- read_csv(file.path(root.dir, "data/2017-2019/2019_chem_preqaqc_SAMPLE-SBU_Mohawk_complete_2020-03-25.csv"))

RESULT.2017 <- read_csv(file.path(root.dir, "data/2017-2019/2017_chem_preqaqc_RESULT-SBU_complete_2020-03-26.csv"), col_types = cols(fraction = col_character()))
RESULT.2018 <- read_csv(file.path(root.dir, "data/2017-2019/2018_chem_preqaqc_RESULT-SBU_complete_2020-03-25.csv"))
RESULT.2019 <- read_csv(file.path(root.dir, "data/2017-2019/2019_chem_preqaqc_RESULT-SBU_Mohawk_complete_2020-03-27.csv"))

BATCH.2017 <- read_csv(file.path(root.dir, "data/2017-2019/2017_chem_preqaqc_BATCH-SBU_complete_2020-03-26.csv"), col_types = cols(fraction = col_character()))
BATCH.2018 <- read_csv(file.path(root.dir, "data/2017-2019/2018_chem_preqaqc_BATCH-SBU_complete_2020-03-26.csv"))
BATCH.2019 <- read_csv(file.path(root.dir, "data/2017-2019/2019_chem_preqaqc_BATCH-SBU_Mohawk_complete_2020-03-26.csv"))

# There appears to be no dissolved (D) fractions in 2017. R detects cols with "T" as logical (TRUE/FALSE) so these col types needed to be specified.

```

Bind SAMPLE, RESULT, and BATCH files by year.
```{r}

sample.all <- bind_rows(SAMPLE.2017, SAMPLE.2018, SAMPLE.2019)
result.all <- bind_rows(RESULT.2017, RESULT.2018, RESULT.2019)
batch.all <- bind_rows(BATCH.2017, BATCH.2018, BATCH.2019)

rm(SAMPLE.2017, SAMPLE.2018, SAMPLE.2019, RESULT.2017, RESULT.2018, RESULT.2019, BATCH.2017, BATCH.2018, BATCH.2019)

```

Test join by sys_sample_code and SDG
```{r}
result.all <- result.all %>% 
  rename(sample_delivery_group = lab_sdg)
test_join_sample.result <- left_join(sample.all, result.all, by = c("sys_sample_code", "sample_delivery_group"))

# CHECKS OUT OKAY. Same number of records created in joined table as in RESULT table.
```

Reformat date fields and headers, add EVENT ID field, add other blank fields
```{r}

sample.all.form <- sample.all %>% 
    rename_all(toupper) %>% 
    rename(DEC_SAMPLE_TYPE_CDE = DEC_SAMPLE_TYPE,
           SYS_SAMPLE_CDE = SYS_SAMPLE_CODE, 
           SAMPLE_MATRIX_CDE = SAMPLE_MATRIX_CODE, 
           LAB_SAMPLE_TYPE_CDE = SAMPLE_TYPE_CODE, 
           PARENT_SAMPLE_CDE = PARENT_SAMPLE_CODE, 
           SAMPLE_DEL_GRP = SAMPLE_DELIVERY_GROUP) %>% 
    mutate(SAMPLE_DATE = as.POSIXct(SAMPLE_DATE, format = "%m/%d/%Y %H:%M:%S" )) %>% 
    mutate(SAMPLE_RECEIPT_DATE = as.Date(SAMPLE_RECEIPT_DATE, format = "%m/%d/%Y")) %>% 
    rename_all(function(x) paste0("CHS_", x)) %>% 
    mutate(CHEM_HISTORY_SAMPLE_ID= "", 
           CREATE_DATE= "", 
           END_DATE= "", 
           UPDATE_DATE= "", 
           UPDATED_BY_GUID= "") %>% 
    mutate(EVENT_ID_DATE = strftime(CHS_SAMPLE_DATE, "%Y%m%d")) %>% 
    mutate(EVENT_SMAS_ID = paste0(CHS_SITE_ID,"_",EVENT_ID_DATE))
 
result.all.form <- result.all %>% 
    rename_all(toupper) %>% 
    rename(SYS_SAMPLE_CDE = SYS_SAMPLE_CODE,
           LAB_ANAL_METHOD_NAME = LAB_ANL_METHOD_NAME,
           LAB_MATRIX_CDE = LAB_MATRIX_CODE,
           LAB_NAME_CDE = LAB_NAME_CODE,
           SUBSAMPLE_AMT = SUBSAMPLE_AMOUNT,
           SUBSAMPLE_AMT_UNIT = SUBSAMPLE_AMOUNT_UNIT,
           RESULT_TYPE_CDE = RESULT_TYPE_CODE,
           REPORTABLE_RESULT_IND = REPORTABLE_RESULT,
           LAB_QUAL = LAB_QUALIFIERS,
           VALIDATOR_QUAL = VALIDATOR_QUALIFIERS,
           INTERPRETED_QUAL = INTERPRETED_QUALIFIERS,
           VALIDATED_IND = VALIDATED_YN,
           METHOD_DETECT_LIMIT = METHOD_DETECTION_LIMIT,
           REPORTING_DETECT_LIMIT = REPORTING_DETECTION_LIMIT,
           QC_ORIG_CONC = QC_ORIGINAL_CONC,
           QC_DUP_ORIG_CONC = QC_DUP_ORIGINAL_CONC,
           SAMPLE_DEL_GRP = SAMPLE_DELIVERY_GROUP) %>% 
    mutate(VALIDATOR_QUAL_REASON_CDE= "",
           VALIDATOR_SAMPLE_ACCURACY= "", 
           VALIDATOR_SAMPLE_PRECISION_FIELD= "",
           VALIDATOR_SAMPLE_PRECISION_LAB= "",
           VALIDATOR_SAMPLE_EQUIP_BLANK= "", 
           VALIDATOR_SAMPLE_PARAM_PAIR= "",
           VALIDATOR_QUAL_EXPLN= "",
           VALIDATION_DATE= "",
           LAB_VALIDATION_LEVEL= NA) %>% 
    mutate(ANALYSIS_DATE = as.POSIXct(ANALYSIS_DATE, format = "%m/%d/%Y %H:%M:%S" )) %>% 
    mutate(PREP_DATE = as.POSIXct(PREP_DATE, format = "%m/%d/%Y %H:%M:%S" )) %>% 
    rename_all(function(x) paste0("CHR_", x)) %>% 
    mutate(CHEM_HISTORY_RESULT_ID= "", 
           CHEM_HISTORY_SAMPLE_ID= "", 
           CHEM_PARAMETER_ID= "", 
           CREATE_DATE= "", 
           END_DATE= "", 
           UPDATE_DATE= "", 
           UPDATED_BY_GUID= "")
      
batch.all.form <- batch.all %>% 
    rename_all(toupper) %>% 
    rename(SYS_SAMPLE_CDE = SYS_SAMPLE_CODE,
           LAB_ANAL_METHOD_NAME = LAB_ANL_METHOD_NAME) %>% 
    mutate(ANALYSIS_DATE = as.POSIXct(ANALYSIS_DATE, format = "%m/%d/%Y %H:%M:%S" )) %>% 
    rename_all(function(x) paste0("CHB_", x)) %>% 
    mutate(CHEM_HISTORY_BATCH_ID= "", 
           CHEM_HISTORY_SAMPLE_ID= "", 
           CREATE_DATE= "", 
           END_DATE= "", 
           UPDATE_DATE= "", 
           UPDATED_BY_GUID= "")


```

Select final headers as per ITS data model
```{r}
# Headers selections below copied directly from the data dictionary, 3/27/20.

# SAMPLE table
sample.all.FINAL <- sample.all.form %>% 
    select(CHEM_HISTORY_SAMPLE_ID, EVENT_SMAS_ID, CHS_SITE_ID_CORR_IND, CHS_DATA_PROVIDER, CHS_SYS_SAMPLE_CDE, 
           CHS_SAMPLE_NAME, CHS_SAMPLE_MATRIX_CDE, CHS_DEC_SAMPLE_TYPE_CDE, CHS_LAB_SAMPLE_TYPE_CDE, CHS_SAMPLE_SOURCE, 
           CHS_PARENT_SAMPLE_CDE, CHS_SAMPLE_DEL_GRP, CHS_SAMPLE_DATE, CHS_SAMPLE_RECEIPT_DATE,
           CHS_SAMPLER, CHS_SAMPLING_COMPANY_CODE, CHS_COMMENT, CREATE_DATE, END_DATE, UPDATE_DATE, 
           UPDATED_BY_GUID)

# RESULT table
result.all.FINAL <- result.all.form %>% 
    select(CHEM_HISTORY_RESULT_ID, CHEM_HISTORY_SAMPLE_ID, CHEM_PARAMETER_ID, CHR_SYS_SAMPLE_CDE, CHR_LAB_ANAL_METHOD_NAME,
           CHR_ANALYSIS_DATE, CHR_FRACTION, CHR_TEST_TYPE, CHR_LAB_MATRIX_CDE, CHR_DILUTION_FACTOR, CHR_PREP_METHOD, 
           CHR_PREP_DATE, CHR_LAB_NAME_CDE, CHR_QC_LEVEL, CHR_LAB_SAMPLE_ID, CHR_SUBSAMPLE_AMT, 
           CHR_SUBSAMPLE_AMT_UNIT, CHR_FINAL_VOLUME, CHR_FINAL_VOLUME_UNIT, CHR_CAS_RN, CHR_CHEMICAL_NAME, CHR_RESULT_VALUE, 
           CHR_RESULT_UNIT, CHR_RESULT_TYPE_CDE, CHR_REPORTABLE_RESULT_IND, CHR_DETECT_FLAG, CHR_LAB_QUAL, CHR_INTERPRETED_QUAL, 
           CHR_VALIDATED_IND, CHR_VALIDATOR_QUAL, CHR_VALIDATOR_QUAL_EXPLN, CHR_VALIDATOR_QUAL_REASON_CDE, CHR_VALIDATION_DATE, 
           CHR_VALIDATOR_SAMPLE_ACCURACY, CHR_VALIDATOR_SAMPLE_PRECISION_FIELD, CHR_VALIDATOR_SAMPLE_PRECISION_LAB, 
           CHR_VALIDATOR_SAMPLE_EQUIP_BLANK, CHR_VALIDATOR_SAMPLE_PARAM_PAIR, CHR_METHOD_DETECT_LIMIT, CHR_REPORTING_DETECT_LIMIT, 
           CHR_QUANTITATION_LIMIT, CHR_DETECTION_LIMIT_UNIT, CHR_VALIDATION_LEVEL, CHR_RESULT_COMMENT, CHR_QC_ORIG_CONC, 
           CHR_QC_SPIKE_ADDED, CHR_QC_SPIKE_MEASURED, CHR_QC_SPIKE_RECOVERY, CHR_QC_DUP_ORIG_CONC, CHR_QC_DUP_SPIKE_ADDED, 
           CHR_QC_DUP_SPIKE_MEASURED, CHR_QC_DUP_SPIKE_RECOVERY, CHR_QC_RPD, CHR_QC_SPIKE_LCL, CHR_QC_SPIKE_UCL, CHR_QC_RPD_CL, 
           CHR_QC_SPIKE_STATUS, CHR_QC_DUP_SPIKE_STATUS, CHR_QC_RPD_STATUS, CHR_SAMPLE_DEL_GRP, CREATE_DATE, END_DATE, UPDATE_DATE, 
           UPDATED_BY_GUID)

# BATCH table
batch.all.FINAL <- batch.all.form %>% 
    select(CHEM_HISTORY_BATCH_ID, CHEM_HISTORY_SAMPLE_ID, CHB_SYS_SAMPLE_CDE, CHB_LAB_ANAL_METHOD_NAME, CHB_ANALYSIS_DATE, 
           CHB_FRACTION, CHB_TEST_TYPE, CHB_TEST_BATCH_TYPE, CHB_TEST_BATCH_ID, CREATE_DATE, END_DATE, UPDATE_DATE, UPDATED_BY_GUID)

```

Export data
```{r}

write.table(sample.all.FINAL, file= paste0(output.path,"/",output.filename.sample),sep=",", row.names = FALSE)
write.table(result.all.FINAL, file= paste0(output.path,"/",output.filename.result),sep=",", row.names = FALSE)
write.table(batch.all.FINAL, file= paste0(output.path,"/",output.filename.batch),sep=",", row.names = FALSE)

```

