---
title: "fish_data"
output: html_document
---

```{r}
library(tidyverse)
library(snakecase)
library(openxlsx)

root.dir <- rprojroot::find_root("chem_hist_cleaning.Rproj")
data.mod.dir <- "C:/Users/gmlemley/New York State Office of Information Technology Services/SMAS - Streams Data Modernization"

fish.mstr <- readxl::read_excel(file.path(data.mod.dir, "to_be_cleaned", "fish", "NYS_FISH_TABLE_2018v2.xlsx"))
fish.sp.data <- readxl::read_excel(file.path(data.mod.dir, "Cleaned Files", "FINAL_RELOADS_SEPT2020", "Final_Fish_ITS", "20201006_S_FISH_SPECIES_DATA_HISTORY.xlsx"))
fish.len <- readxl::read_excel(file.path(data.mod.dir, "Cleaned Files", "FINAL_RELOADS_SEPT2020", "Final_Fish_ITS", "20201006_S_FISH_SPEC_SAMP_LENGTH_HIST.xlsx"))

```

Master species table cleaning
```{r}
fish.mstr.edit <- fish.mstr %>%
  select(-...10) %>% 
  rename(GENSPECIES = Genus_species,
         TAXONOMIC_SERIAL_NUM = TSN) %>% 
  rename_all(toupper) %>%
  rename_all(function(x) gsub(" ", "_", x)) %>% 
  rename_all(function(x)
    paste0("MFS_", x)) %>% 
  mutate(MFS_COMMON_FAMILY_NAME = to_title_case(MFS_COMMON_FAMILY_NAME, sep_in = "_")) %>% 
  mutate(MFS_COMMON_FAMILY_NAME = str_replace(MFS_COMMON_FAMILY_NAME, "Bullhead", "Bullheads")) %>% 
  mutate(MFS_COMMON_FAMILY_NAME = str_replace(MFS_COMMON_FAMILY_NAME, "Carp", "Carps")) %>% 
  mutate(MFS_COMMON_FAMILY_NAME = str_replace(MFS_COMMON_FAMILY_NAME, "Trout-Perches", "Trout-perches")) %>% 
  mutate(MFS_COMMON_NAME = to_title_case(MFS_COMMON_NAME, sep_in = "_")) %>% 
  mutate(MFS_COMMON_NAME = str_replace(MFS_COMMON_NAME, "Lamprey\\(Ammocoete\\)", "Lamprey (Ammocoete)")) %>% 
  mutate(MFS_COMMON_NAME = str_replace(MFS_COMMON_NAME, "Trout-Perch", "Trout-perch")) %>% 
  na_if(., "na") %>% 
  mutate(MFS_SENSITIVITY = str_replace(MFS_SENSITIVITY, "\\?", "")) %>% 
  mutate(MFS_SENSITIVITY = str_replace(MFS_SENSITIVITY, "1, 3", "1,3")) %>% 
  mutate(MFS_REPRODUCTIVE_BEHAVIOR = toupper(MFS_REPRODUCTIVE_BEHAVIOR)) %>% 
  mutate(MFS_TROPHIC_LEVEL = toupper(MFS_TROPHIC_LEVEL))

# Test join with FISH_SPECIES_DATA_HISTORY table
fish.sp.data.join <- fish.sp.data %>% 
  rename(MFS_GENSPECIES = FSDH_GENSPECIES) %>% 
  left_join(fish.mstr.edit, by = "MFS_GENSPECIES")

# Test join with LENGTH table
fish.mstr.len.join <- fish.len %>% 
  rename(MFS_GENSPECIES = FSSLH_GENSPECIES) %>% 
  left_join(fish.mstr.edit, by = "MFS_GENSPECIES")  


```

```{r}
# write_csv(fish.mstr.edit, file.path(data.mod.dir, "Cleaned Files", "FINAL_RELOADS_SEPT2020", "Final_Fish_ITS", "20201009_S_MSTR_FISH_SPECIES.xlsx"), na = "")
write.xlsx(fish.mstr.edit, file.path(data.mod.dir, "Cleaned Files", "FINAL_RELOADS_SEPT2020", "Final_Fish_ITS", "20201009_S_MSTR_FISH_SPECIES.xlsx"))
```

