---
title: "historic_chem_updates_2022-03-07"
author: "glemley"
date: "3/7/2022"
output: html_document
---

```{r Load in libs, set project dirs}
library(tidyverse)

root.dir <- rprojroot::find_root("chem_hist_cleaning.Rproj")
datamod.dir <- "C:/Users/gmlemley/New York State Office of Information Technology Services/SMAS - Streams Data Modernization/Cleaned Files/"

```

```{r Load in master chem tables and pcodes}

chem.sample <- read.csv(file.path(datamod.dir, "Final_Chemistry_ITS", "MASTER_S_CHEM_HISTORY_SAMPLE_2021-12-27.csv"))
chem.result.m <- read.csv(file.path(datamod.dir, "Final_Chemistry_ITS", "MASTER_S_CHEM_HISTORY_RESULT_2021-05-03.csv"))

```

```{r Converting pre-2018 lab flags}

## The validator qualifiers indicate flags produced by the QA/QC script.
## The QA/QC script was not developed/used until 2018.
## The following code populates the the pre-2018 with the most comprehensive
## flag that can be applied at this time based on the available lab qualifiers.

# Pull date from sample table for subsetting
chem.sample.date <- chem.sample %>%
  select(CHS_SYS_SAMPLE_CDE, CHS_SAMPLE_DEL_GRP, CHS_EVENT_SMAS_SAMPLE_DATE)

# Join date, filter to pre-2018, and filter to just records with flags we will convert.
chem.r.update <- chem.result.m %>%
  left_join(chem.sample.date, by = c("CHR_SYS_SAMPLE_CDE" = "CHS_SYS_SAMPLE_CDE", "CHR_SAMPLE_DEL_GRP" = "CHS_SAMPLE_DEL_GRP")) %>%
  mutate(date = as.Date(CHS_EVENT_SMAS_SAMPLE_DATE, "%m/%d/%Y")) %>%
  filter(date < as.Date("2018-01-01")) %>%
  filter(grepl("B|N|\\*|D|W|E|J|U", CHR_LAB_QUAL))

# Set aside old records to be deleted from DB
chem.r.delete <- chem.r.update %>%
  select(-CHS_EVENT_SMAS_SAMPLE_DATE, -date)

# Convert lab flags to validator qualifiers
chem.r.update2 <- chem.r.update %>%
  mutate(
    CHR_VALIDATOR_QUAL = case_when(
      grepl("B|N|\\*|D|W", CHR_LAB_QUAL) ~ "R",
      grepl("E|J", CHR_LAB_QUAL) ~ "J",
      grepl("U", CHR_LAB_QUAL) ~ "U",
      TRUE ~ CHR_VALIDATOR_QUAL
    )
  ) %>%
  select(-CHS_EVENT_SMAS_SAMPLE_DATE, -date)

### Delete/append old/new records to the master result table
chem.result.new <- chem.result.m %>%
  anti_join(chem.r.delete) %>%
  bind_rows(chem.r.update2)

#93,377 records updated

```

```{r  Apply flags to TN and nitrate data based on parent param flags}

# Re-add sample date to updated results data frame
chem.result.new <- chem.result.new %>%
  left_join(chem.sample.date, by = c("CHR_SYS_SAMPLE_CDE" = "CHS_SYS_SAMPLE_CDE", "CHR_SAMPLE_DEL_GRP" = "CHS_SAMPLE_DEL_GRP"))

# Load pcode table to get pcodes
# pcode <- read.csv(file.path(datamod.dir, "Final_Chemistry_ITS", "MASTER_S_CHEM_PARAMETER_2022-03-03.csv"))

### Updating nitrate and TN flags based on two chunks copied from QAQC script.

### Nitrate Flags
# If Nitrate/Nitrite or Nitrite parameters are flagged as R (rejected) or T (trend) then these flags are transferred to Nitrate in that priority (R is added over T if both are listed for that sys_sample_code).

# pcodes:
# 100 = NITRATE
# 101 = NITRATE-NITRITE
# 102 = NITRITE

new_codes.no3<-chem.result.new %>% 
  filter(CHR_PCODE==102) %>% select(CHR_SYS_SAMPLE_CDE,CHS_EVENT_SMAS_SAMPLE_DATE) %>% distinct()
if(nrow(new_codes.no3)>0){
  noxni<-chem.result.new %>% filter(CHR_PCODE %in% c(101, 102)) %>% distinct()
  new_codes.no3<-merge(new_codes.no3,noxni,by=c('CHR_SYS_SAMPLE_CDE','CHS_EVENT_SMAS_SAMPLE_DATE'),all.x = TRUE)
  new_codes.no3<-new_codes.no3 %>% 
    select(CHR_SYS_SAMPLE_CDE,CHR_VALIDATOR_QUAL) %>% distinct() %>% 
    filter(!is.na(CHR_VALIDATOR_QUAL),
           CHR_VALIDATOR_QUAL %in% c('R','T')) %>% 
    arrange(CHR_SYS_SAMPLE_CDE,CHR_VALIDATOR_QUAL) %>% 
    #since these are arranged alphabetically, the R will be accepted over T
    distinct(CHR_SYS_SAMPLE_CDE,.keep_all = TRUE) %>% 
    mutate(new_codes.no3=CHR_VALIDATOR_QUAL) %>% 
    select(CHR_SYS_SAMPLE_CDE,new_codes.no3) %>% distinct()
  chem.result.new.2<-merge(chem.result.new,new_codes.no3,by=c('CHR_SYS_SAMPLE_CDE'),all=TRUE)
  chem.result.new.3<-chem.result.new.2 %>% 
    mutate(CHR_VALIDATOR_QUAL=ifelse(!is.na(new_codes.no3)&CHR_PCODE==100,new_codes.no3,CHR_VALIDATOR_QUAL)) %>% 
    select(-new_codes.no3) %>% 
    mutate(CHR_VALIDATOR_QUAL_EXPLN=ifelse(CHR_VALIDATOR_QUAL %in% c('R','T')&CHR_PCODE==100,"calculated parameter_see components",CHR_VALIDATOR_QUAL_EXPLN))
  # rm(noxni)
}

# pcodes:
# 99 = TKN
# 101 = NITRATE-NITRITE
# 103 = TN

### Total Nitrogen Flags
# If TKN or NOX parameters are flagged as R (rejected) or T (trend) then these flags are transferred to Total Nitrogen in that priority (R is added over T if both are listed for that sys_sample_code).

new_codes.tn<-chem.result.new.3 %>% filter(CHR_PCODE==103) %>% select(CHR_SYS_SAMPLE_CDE,CHS_EVENT_SMAS_SAMPLE_DATE) %>% distinct()
if(nrow(new_codes.tn)>0){
  nox_tkn<-chem.result.new.3 %>% filter(CHR_PCODE %in% c(101,99)) %>% distinct()
  new_codes.tn<-merge(new_codes.tn,nox_tkn,by=c('CHR_SYS_SAMPLE_CDE','CHS_EVENT_SMAS_SAMPLE_DATE'),all.x = TRUE)
  new_codes.tn<-new_codes.tn %>% 
    select(CHR_SYS_SAMPLE_CDE,CHR_VALIDATOR_QUAL) %>% distinct() %>% 
    filter(!is.na(CHR_VALIDATOR_QUAL),
           CHR_VALIDATOR_QUAL %in% c('R','T')) %>% 
    arrange(CHR_SYS_SAMPLE_CDE,CHR_VALIDATOR_QUAL) %>% 
    #since these are arranged alphabetically, the R will be accepted over T
    distinct(CHR_SYS_SAMPLE_CDE,.keep_all = TRUE) %>% 
    mutate(new_codes.tn=CHR_VALIDATOR_QUAL) %>% 
    select(CHR_SYS_SAMPLE_CDE,new_codes.tn) %>% distinct()
  chem.result.new.4<-merge(chem.result.new.3,new_codes.tn,by=c('CHR_SYS_SAMPLE_CDE'),all=TRUE)
  chem.result.new.4<-chem.result.new.4 %>% 
    mutate(CHR_VALIDATOR_QUAL=ifelse(!is.na(new_codes.tn)&CHR_PCODE==103,new_codes.tn,CHR_VALIDATOR_QUAL)) %>% 
    select(-new_codes.tn) %>% 
    mutate(CHR_VALIDATOR_QUAL_EXPLN=ifelse(CHR_VALIDATOR_QUAL %in% c('R','T')&CHR_PCODE==103,"calculated parameter_see components",CHR_VALIDATOR_QUAL_EXPLN))
  # rm(nox_tkn)
}

# Remove added sample date field
chem.result.new.4 <- chem.result.new.4 %>%
  select(-CHS_EVENT_SMAS_SAMPLE_DATE)

# 964 records updated

```

```{r Clean up result values}

# Remove non-detect result values that were set to MDL/QL in EQuIS
chem.result.new.u <- chem.result.new.4 %>%
  # filter(CHR_LAB_QUAL %in% "U",
  #        !is.na(CHR_RESULT_VALUE)) %>%
  mutate(CHR_RESULT_VALUE = ifelse(CHR_LAB_QUAL %in% "U" & !is.na(CHR_RESULT_VALUE), NA, CHR_RESULT_VALUE))

chem.r.new.u <- chem.result.new.u %>%
  anti_join(chem.result.new.4)
chem.r.delete.u <- chem.result.new.4 %>%
  anti_join(chem.result.new.u)

# 14,982 records updated

```

```{r Exporting}

# Now get the records that have changed from the original input file, for exporting for ITS (recs to delete/append) and update master table
chem.r.new <- chem.result.new.u %>%
  anti_join(chem.result.m)
chem.r.delete <- chem.result.m %>%
  anti_join(chem.result.new.u)

# Export records for ITS to delete from DB
write.table(chem.r.delete, file = file.path(datamod.dir,"Final_Chemistry_ITS", "2021_UPDATES", "DELETE_RECS-S_CHEM_HISTORY_RESULT.csv"),sep=",", row.names = FALSE, na = "")
# Export records for ITS to append to DB
write.table(chem.r.new, file = file.path(datamod.dir,"Final_Chemistry_ITS", "2021_UPDATES", "APPEND_RECS-S_CHEM_HISTORY_RESULT.csv"),sep=",", row.names = FALSE, na = "")

# Export new results master table
write.table(chem.result.new.u, file = file.path(datamod.dir,"Final_Chemistry_ITS", "MASTER_S_CHEM_HISTORY_RESULT_2022-03-08.csv"),sep=",", row.names = FALSE, na = "")


```

