---
title: "pcode_final"
output: html_document
---

Load in libs, set project dirs
```{r}
library(tidyverse)

root.dir <- rprojroot::find_root("chem_hist_cleaning.Rproj")

```


Load in draft pcode table and format
```{r}
pcode.draft.input <- readxl::read_excel(file.path(root.dir, "parameters", "pcode_table_FINAL_CODES_2020-10-13.xlsx")) 

pcode.final <- pcode.draft.input %>%   
    rename(
    PCODE = DEC_pcode_FINAL,
    NAME = chemical_name,
    UNIT = result_unit,
    UNIT_NOSP = result_unit_no_sp_chars,
    FRACTION = fraction,
    SOURCE = RESULT_TYPE,
    NOTES = Notes_final
  ) %>% 
  mutate(PCODE = sprintf("%03d", PCODE)) %>% 
  mutate(SOURCE = toupper(SOURCE)) %>% 
  mutate(FRACTION = case_when(
    FRACTION == "T" ~ "TOTAL",
    FRACTION == "D" ~ "DISSOLVED",
    TRUE ~ FRACTION)) %>% 
  rename_all(function(x)
    paste0("CHEM_PARAMETER_", x)) %>% 
  select(CHEM_PARAMETER_PCODE,
         CHEM_PARAMETER_NAME,
         CHEM_PARAMETER_UNIT,
         CHEM_PARAMETER_UNIT_NOSP,
         CHEM_PARAMETER_FRACTION,
         CHEM_PARAMETER_SOURCE,
         # CHEM_PARAMETER_GROUP,
         CHEM_PARAMETER_NOTES
         )

write.table(pcode.final, file = file.path(root.dir, "data", "2018-2019_ITS_2020-10-05", "S_CHEM_PARAMETER.csv"),sep=",", row.names = FALSE,  na = "")


```

Trim down historic pcode join table to current params only for joining pcodes to incoming data. 
```{r}
# Lakes new pcode join from Alene: chem_hist_cleaning\parameters\L_PCODE (2).csv
#    Trimmed down from 8-24 version, used all historic data (which was cleaned)

# Import 8-24 version and trim down to unique chemical_names/fractions/result_units in CLEANED 2018-2019 data 
#    Bind to L_PCODE above, format consistently, and take unique of the 3 fields.
#    Inlude all PCBs so general pcode can be applied.
#    Make sure selenium was removed...

```

